# Generated by Django 5.0.6 on 2024-12-07 01:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0004_deleteview_delete_organizationsettings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="slug",
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
