# Generated by Django 5.0.6 on 2025-01-06 22:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0005_alter_organization_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationlabels",
            name="department_label",
            field=models.CharField(default="Department", max_length=50),
        ),
        migrations.AddField(
            model_name="organizationlabels",
            name="quarters_label",
            field=models.CharField(default="Quarters", max_length=50),
        ),
    ]
