# Generated by Django 5.2.8 on 2025-11-19 10:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0006_organizationlabels_department_label_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="organization",
            constraint=models.UniqueConstraint(
                fields=("parent", "slug"), name="unique_org_slug_per_parent"
            ),
        ),
    ]
