# Generated by Django 5.2.8 on 2025-11-19 10:55

import address.models
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("address", "0003_auto_20200830_1851"),
        ("organization", "0007_organization_unique_org_slug_per_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="address",
            field=address.models.AddressField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_address",
                to="address.address",
            ),
        ),
    ]
